Controllers films users
isalamatov/java-filmorate pull request #1
Opened 2022-09-07 14:13 UTC by isalamatov

2022-09-08 19:28 UTC, chewmag requested changes
Приветствую Игорь!

Критичных замечаний в работе нет, исправления не требуются. Предлагаю пройти по комментариям и реализовать улучшения, или оставить все как есть :)

2022-09-08 19:28 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films.get(film.getId());
Проще вернуть film, только что положенный в мапу, а не доставить его из нее )

2022-09-08 19:28 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films.get(id.get());
Проще вернуть film, только что положенный в мапу, а не доставить его из нее )

2022-09-08 19:28 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Optional<Integer> id = Optional.ofNullable(film.getId());
Проще не мудрить с Optional а просто проверить film.getId() на null

2022-09-08 19:28 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return users.get(user.getId());
Проще вернуть user, только что положенный в мапу, а не доставить его из нее )

2022-09-08 19:28 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return users.get(user.getId());
Проще вернуть user'a, только что положенный в мапу, а не доставить его из нее )

2022-09-08 19:28 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/handlers/ValidatorHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
Разделить бы пустой строкой )

2022-09-08 19:28 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/validator/Birthday.java
> +
Аннотации улетели )

2022-09-09 08:40 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films.get(film.getId());
Исправил. Логика была в том, чтобы полностью проверить, что объект получен и правильно обработан. Но это, вероятно, лучше проверять через механизмы журналирования, а не замедлять работу программы )

2022-09-09 08:40 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return films.get(id.get());
Исправил

2022-09-09 08:43 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Optional<Integer> id = Optional.ofNullable(film.getId());
Логика проверки - если id пустой - генерируем новый id. Если не пустой, и фильм с таким id уже есть в БД - генерируем ValidationException. Если id существует и не содержится в коллекции - добавляем фильм. Если убрать optional то код сильно не упростится, на мой взгляд. Если логика не правильная - готов исправить.

2022-09-09 08:43 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return users.get(user.getId());
Исправил

2022-09-09 08:43 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        return users.get(user.getId());
Исправил

2022-09-09 08:43 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/handlers/ValidatorHandler.java
> +    @ExceptionHandler(MethodArgumentNotValidException.class)
Исправил

2022-09-09 08:43 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/validator/Birthday.java
> +
Исправил

2022-09-10 06:45 UTC, chewmag approved these changes
Здравствуйте Игорь!

Улучшения реализованы (кроме использования Optional, но оставим как есть), можно мерджить реквест в main 👍

2022-09-10 06:45 UTC, chewmag commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        Optional<Integer> id = Optional.ofNullable(film.getId());
Это да, но я имел в виду что все это можно сделать без Optional.

2022-09-10 07:18 UTC, merged