refactor: Added database storage
isalamatov/java-filmorate pull request #4
Opened 2022-10-12 12:08 UTC by isalamatov

2022-10-13 04:13 UTC, sergeymamonov requested changes
Зачем создавать несколько файлов с созданием таблиц? Лучше сделать один файл, где создаются таблицы. И не дублировать это действие.
Размер varchar необходимо ограничивать количеством символов.
Вся валидация должна быть в сервисе, например
if (count < 0) {
            throw new ValidationException("Count must be positive number");
}
 нужно перенести в сервис, а оставлять в домене.

Зачем так делать? А если в БД миллионы записей? И чтобы найти один фильм будем запрашивать все фильмы?
if (filmService.getAll().stream().noneMatch(x -> x.getId() == result)) {
            throw new FilmNotFoundException(result);
}

parseUserId не нужно искать одного юзера через запрос всех юзером. Валидацию нужно перенести в сервис.

2022-10-13 04:13 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +//        friend.getFriendsId().add(mainId);
Удалить весь закомментированный код.

2022-10-13 04:13 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DBFilmStorage.java
> +        film.getGenres().forEach(genre ->
Не нужно делать запросов к БД в цикле. Поищите вариант сделать одним запросом. Далее аналогично. Не нужно грузить БД в цикле. Нужно стараться делать как можно меньше запросов к БД.

2022-10-13 04:13 UTC, sergeymamonov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DBFilmStorage.java
> +        } catch (FilmNotFoundException exception) {
В этой строке поймали исключение, в следующей бросили это же самое исключение. Какой в этом смысл?

2022-10-13 15:53 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +        return filmService.get(film.getId());
К сожалению не смог устранить данное замечание разумным способом. В одном из тестов postman необходимо возвращать объект с вложенными множествами объектов (mpa, genre id). В самом объекте во множестве есть дубли, и проверочный скрипт теста ожидает, что они будут устранены при обработке. Если вернуть сам объект в ответ, тест не засчитывается как успешный. Можно конечно сделать "костыль" с проверкой дублей в id множества, только чтобы пройти данный тест, но мне показалось это избыточным, и проще вернуть измененный объект из базы. Если его "прокидывать" из слоя dao - для его сборки мне все равно придется делать несколько операций чтения из базы после апдейта записей в ней, или для поиска текстовых значений полей справочников, т.е. снизить нагрузку на базу существенно не получится. Возможно, я что-то не верно истолковал.

2022-10-13 15:53 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/model/Mpa.java
> +    public Mpa() {
Исправил.

2022-10-13 15:53 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/service/UserService.java
> +//        friend.getFriendsId().add(mainId);
Удалил

2022-10-13 16:10 UTC, isalamatov commented on src/main/java/ru/yandex/practicum/filmorate/storage/impl/DBFilmStorage.java
> +        } catch (FilmNotFoundException exception) {
Исправлено. Проверка наличия объектов вынесена в сервисный уровень. В интерфейсы dao добавлены методы check*.

2022-10-14 14:43 UTC, sergeymamonov approved these changes

2022-10-16 07:48 UTC, merged